name: build-test-deploy
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      node-version:
        description: 'Node version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      # Modified to use the node-version from the workflow inputs
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install and build
        run: |
          npm install
          npm run build --if-present

      - name: Run tests
        run: |
          echo ${{ matrix.node-version }}
          echo "Hello, world!" ${{ matrix.node-version }} > output_${{ matrix.node-version }}.txt

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ github.sha }}'
          release_name: Release ${{ github.sha }}
          body: |
            **Changes:**
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output_${{ matrix.node-version }}.txt
          path: './output_${{ matrix.node-version }}.txt'
